# Generated by Django 3.1.4 on 2020-12-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20201222_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий к постам', 'verbose_name_plural': 'Комментарии к постам'},
        ),
    ]
