# Generated by Django 3.1.4 on 2020-12-28 17:09

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title ')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео',
            },
        ),
    ]
