# Generated by Django 3.1.4 on 2020-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='football_videos',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title '),
        ),
    ]
